#!/bin/sh

[ "$(uci get system.@system[-1].fb)" = "1" ] && return 0

. /lib/ramips.sh
board=$(ramips_board_name)

if [ "$board" == "wizfi630s" ]
then
	echo "WizFi630S Firstboot process" > /dev/console
	/etc/init.d/wizfi630s_init enable
	/etc/init.d/wizfi630s_init start
fi
