#!/bin/sh

. /lib/functions.sh
. /lib/functions/system.sh

[ "$(uci get system.@system[-1].fb)" = "1" ] && return 0

uci set system.@system[-1].hostname="wizfi630s"


MAC=$(dd bs=1 skip=7 count=3 if=/dev/mtd2 2>/dev/null | hexdump -v -n 3 -e '3/1 "%02X"')
SSID=WizFi630S_AP_${MAC}

uci set wireless.radio0.disabled=0

#daniel delete default wifi-iface setting
uci delete wireless.@wifi-iface[0]

#daniel set default AP config
uci set wireless.ap=wifi-iface
uci set wireless.ap.mode=ap
uci set wireless.ap.network=lan
uci set wireless.ap.ifname=ra0
uci set wireless.ap.ssid="$SSID"
uci set wireless.ap.device=radio0
uci set wireless.ap.encryption=none
uci set wireless.ap.disabled=0
#uci set wireless.ap.disabled=1

#daniel 181031 set default STA config
uci set wireless.sta=wifi-iface
uci set wireless.sta.mode=sta
uci set wireless.sta.network=wwan
uci set wireless.sta.ifname=apcli0
uci set wireless.sta.device=radio0
uci set wireless.sta.ssid=MyRouter
uci set wireless.sta.key=MyPassword
uci set wireless.sta.encryption=psk2
uci set wireless.sta.disabled=1
#uci set wireless.sta.disabled=0

#daniel 181031 set eth LAN  interface
#uci set network.lan.ifname=eth0.1
#uci set network.lan.ipaddr=192.168.3.1
uci set network.lan.force_link=1

#daniel 181031 set wifi STA interface
#uci set network.wifi=interface
#uci set network.wifi.proto=static
#uci set network.wifi.ipaddr=192.168.2.1
#uci set network.wifi.netmask=255.255.255.0
 
#daniel 181031 set eth WAN interface
#uci set network.wan=interface
#uci set network.wan.proto=dhcp
#uci set network.wan.ifname=eth0.2
#uci set network.wan.force_link=1


#daniel 181031 set wifi AP interface
uci set network.wwan=interface
uci set network.wwan.proto=dhcp
#uci set network.wwan.ifname=apcli0
#uci set network.wwan.force_link=1

#daniel 181031 set eth WAN v6 interface
#uci set network.wan6=interface
#uci set network.wan6.proto=dhcpv6
#uci set network.wan6.ifname=eth0.2

#daniel 181031 set switch enable
#uci add network switch
#uci set network.@switch[0].name=switch0
#uci set network.@switch[0].reset=1
#uci set network.@switch[0].enable_vlan=1

#daniel 181031 set 3,4 port to virtual LAN
#uci add network switch_vlan
#uci set network.@switch_vlan[0].device=switch0
#uci set network.@switch_vlan[0].vlan=1
#uci set network.@switch_vlan[0].ports='3 4 6t'

#daniel 181031 set 0 port to virtual WAN
#uci add network switch_vlan
#uci set network.@switch_vlan[1].device=switch0
#uci set network.@switch_vlan[1].vlan=2
#uci set network.@switch_vlan[1].ports='0 6t'

#daniel 181031 set wwan to dhcp
uci set dhcp.wwan=dhcp
uci set dhcp.wwan.interface=wwan

#daniel 181031 set AP mode to dhcp server
#uci set dhcp.wifi=dhcp
#uci set dhcp.wifi.start=100
#uci set dhcp.wifi.limit=150
#uci set dhcp.wifi.leasetime=12h
#uci set dhcp.wifi.interface=wifi

#daniel 181031 set LAN port to dhcp server
#uci set dhcp.lan.start=100
#uci set dhcp.lan.limit=150
#uci set dhcp.lan.leasetime=12h

#daniel 181031 add wifi network to firewall
#uci add_list firewall.@zone[0].network=wifi
uci add_list firewall.@zone[1].network=wwan
uci set firewall.@zone[1].input=ACCEPT

#daniel 190125 del wifi ifname, no needed.
#uci delete network.wwan.ifname
#uci delete network.wifi.ifname

#uci set network.wifi.ipaddr=192.168.2.1

uci commit
return 0
